name: Stocklet
description: A fun, modern looking stock simulator app

version: 0.9.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Our source of ads
  admob_flutter: ^0.3.4

  # ID gen
  device_info: ^0.4.2+4

  # Notifications for watched stocks
  onesignal_flutter: ^2.0.0

  # HTTP plugin for talking to the API
  http: ^0.12.0+4

  # Currently unused Recaptcha plugin for verifying users.
  # TODO implement usage
  recaptchav2_plugin: ^1.0.0

  # Chart package used in the summary page
  fl_animated_linechart: ^1.1.3

  # Provider package, useful for utility things and cleaning up code
  provider: ^4.1.2

  # Dev google font dependency
  # TODO remove and add TTF fonts
  google_fonts: ^1.1.0

  # A nice animation sequencer tool, used in the star animation
  flutter_sequence_animation: ^3.0.1

  # Insanely fast database, used for caching everything
  hive: ^1.4.1+1

  # Adds some nice functionality to listen for changes, and to have a nicer init method.
  hive_flutter: ^0.3.0+2

  # DateFormatting and NumberFormatting tools
  intl: ^0.16.1

  # Shows a popup CircularProgressIndicator
  modal_progress_hud: ^0.1.3

dev-dependencies:
  # Generates type adapters to serialize Users and Stocks
  hive_generator: ^0.7.0+2

  # Used by hive generator
  build_runner: ^1.10.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/temp_logo.png

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700

    - family:  StockSimIcons
      fonts:
        - asset: assets/fonts/StockSimIcons.ttf